# Generated by Django 5.2.4 on 2025-07-03 16:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('idCarg', models.AutoField(primary_key=True, serialize=False)),
                ('nomeCarg', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'Cargo',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('idDepa', models.AutoField(primary_key=True, serialize=False)),
                ('nomeDepa', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'Departamento',
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('idEnde', models.AutoField(primary_key=True, serialize=False)),
                ('cepEnde', models.CharField(blank=True, max_length=10, null=True)),
                ('logadouroEnde', models.TextField()),
                ('numeroEnde', models.CharField(blank=True, max_length=10, null=True)),
                ('complementoEnde', models.TextField(blank=True, null=True)),
                ('bairroEnde', models.TextField()),
                ('cidadeEnde', models.TextField()),
            ],
            options={
                'db_table': 'Endereco',
            },
        ),
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('idPlan', models.AutoField(primary_key=True, serialize=False)),
                ('nomePlan', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'Plano',
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('idVeic', models.AutoField(primary_key=True, serialize=False)),
                ('nomeVeic', models.CharField(max_length=100)),
                ('anoVeic', models.SmallIntegerField(blank=True, null=True)),
                ('placaVeic', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'Veiculo',
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('idPess', models.AutoField(primary_key=True, serialize=False)),
                ('nomePess', models.CharField(max_length=255)),
                ('telefonePess', models.CharField(blank=True, max_length=20, null=True)),
                ('documentoPess', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('nascimentoPess', models.DateField(blank=True, null=True)),
                ('emailPess', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('usuarioPess', models.CharField(max_length=150, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('idEndePess', models.OneToOneField(blank=True, db_column='idEndePess', null=True, on_delete=django.db.models.deletion.SET_NULL, to='membertruck_app.endereco')),
            ],
            options={
                'verbose_name_plural': 'Pessoas',
                'db_table': 'Pessoa',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('idFunc', models.AutoField(primary_key=True, serialize=False)),
                ('salarioFunc', models.FloatField(blank=True, null=True)),
                ('comissaoFunc', models.FloatField(blank=True, null=True)),
                ('dataAdmissaoFunc', models.DateField(blank=True, null=True)),
                ('idCargFunc', models.ForeignKey(blank=True, db_column='idCargFunc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='membertruck_app.cargo')),
                ('idDepaFunc', models.ForeignKey(blank=True, db_column='idDepaFunc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='membertruck_app.departamento')),
                ('idPessFunc', models.OneToOneField(db_column='idPessFunc', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Funcionario',
            },
        ),
        migrations.CreateModel(
            name='Associado',
            fields=[
                ('idAsso', models.AutoField(primary_key=True, serialize=False)),
                ('dataAtivacaoAsso', models.DateField(blank=True, null=True)),
                ('dataPagamentoAsso', models.DateField(blank=True, null=True)),
                ('idPessAsso', models.OneToOneField(db_column='idPessAsso', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('idPlanAsso', models.ForeignKey(blank=True, db_column='idPlanAsso', null=True, on_delete=django.db.models.deletion.SET_NULL, to='membertruck_app.plano')),
                ('idVeicAsso', models.ForeignKey(blank=True, db_column='idVeicAsso', null=True, on_delete=django.db.models.deletion.SET_NULL, to='membertruck_app.veiculo')),
            ],
            options={
                'db_table': 'Associado',
            },
        ),
    ]
