# Generated by Django 5.2.4 on 2025-07-05 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membertruck_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='associado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='veiculos', to='membertruck_app.associado'),
        ),
        migrations.AlterField(
            model_name='associado',
            name='idVeicAsso',
            field=models.ForeignKey(blank=True, db_column='idVeicAsso', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='veiculos_associado', to='membertruck_app.veiculo'),
        ),
    ]
